# Generated by Django 3.1.4 on 2020-12-27 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('school_type', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField()),
                ('established', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('dob', models.DateField()),
                ('address', models.CharField(max_length=150)),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('father_phone_number', models.IntegerField()),
                ('mother_phone_number', models.IntegerField()),
                ('father_occupation', models.CharField(max_length=100)),
                ('mother_occupation', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('salary', models.FloatField()),
                ('school', models.ManyToManyField(to='school_management.School')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subject_faculty', models.ManyToManyField(to='school_management.Faculty')),
                ('subject_teacher', models.ManyToManyField(to='school_management.Teacher')),
            ],
        ),
        migrations.AddField(
            model_name='school',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_management.student'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='school_management.student'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='teacher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='school_management.teacher'),
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('exam_date', models.DateTimeField()),
                ('student_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_management.student')),
            ],
        ),
    ]
